# Set docker-compose version
version: '3'

services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    # volumes:
    #   - ./tmp/db:/var/lib/postgresql/data
    # volumes:
    #   - postgres-vol:/var/lib/postgresql/data
  # webpacker:
  #   container_name: webpacker
  #   build: .
  #   command: ./bin/webpack-dev-server
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '3035:3035'
  #   env_file:
  #     - '.env.docker'
  web:
    build: .
    ports:
      - "3000:3000"
    command: -c "bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      # - webpacker
    env_file:
      - '.env.docker'