# Set docker-compose version
version: '3'

services:
  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - $HOME/postgres-data:/var/lib/postgresql
    image: postgres:9.6.9
  webpacker:
    container_name: webpacker
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
    ports:
      - '3035:3035'
    env_file:
      - '.env.docker'
  web:
    container_name: web
    build: .
    ports:
      - "3000:3000"
    command: /bin/sh -c "rails s -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - webpacker
    env_file:
      - '.env.docker'