class PersonalQuestionnaireSerializer < ActiveModel::Serializer
  attributes :id,
  :birthdate,
  :phone_number,
  :pronouns,
  :race_and_ethnicities,
  :drivers_license_status,
  :emergency_contact_name,
  :emergency_contact_phone_number,
  :emergency_contact_relationship,
  :emergency_contact_2_name,
  :emergency_contact_2_phone_number,
  :emergency_contact_2_relationship,
  :significant_relationships,
  :support_systems,
  :mental_health,
  :DOC_status,
  :DOC_regulations,
  :housing,
  :medical,
  :treatment,
  :triggers_and_prevention,
  :personal_needs,
  :transportation,
  :clothing,
  :financial_obligations,
  :resources_allocated,
  :orca_card,
  :state_assistance,
  :personal_goals,
  :participant

  belongs_to :participant, serializer: SimpleParticipantSerializer
end
