class ReorderQuestionnaireColumns < ActiveRecord::Migration[6.0]
  def change
    remove_column :personal_questionnaires, :doc_status, :string
    remove_column :personal_questionnaires, :housing, :string
    remove_column :personal_questionnaires, :mental_health, :string
    remove_column :personal_questionnaires, :medical, :string
    remove_column :personal_questionnaires, :transportation, :string
    remove_column :personal_questionnaires, :clothing, :string
    remove_column :personal_questionnaires, :significant_relationships, :string
    remove_column :personal_questionnaires, :support_systems, :string
    remove_column :personal_questionnaires, :doc_regulations, :string
    remove_column :personal_questionnaires, :treatment, :string
    remove_column :personal_questionnaires, :triggers_and_prevention, :string
    remove_column :personal_questionnaires, :personal_needs, :string
    remove_column :personal_questionnaires, :personal_goals, :string
    remove_column :personal_questionnaires, :birthdate, :datetime
    remove_column :personal_questionnaires, :phone_number, :string
    remove_column :personal_questionnaires, :pronouns, :string
    remove_column :personal_questionnaires, :race_and_ethnicities, :string
    remove_column :personal_questionnaires, :drivers_license_status, :string
    remove_column :personal_questionnaires, :emergency_contact_name, :string
    remove_column :personal_questionnaires, :emergency_contact_phone_number, :string
    remove_column :personal_questionnaires, :emergency_contact_relationship, :string
    remove_column :personal_questionnaires, :emergency_contact_2_name, :string
    remove_column :personal_questionnaires, :emergency_contact_2_phone_number, :string
    remove_column :personal_questionnaires, :emergency_contact_2_relationship, :string
    remove_column :personal_questionnaires, :financial_obligations, :string
    remove_column :personal_questionnaires, :resources_allocated, :string
    remove_column :personal_questionnaires, :orca_card, :string
    remove_column :personal_questionnaires, :state_assistance, :string

    add_column :personal_questionnaires, :birthdate, :datetime
    add_column :personal_questionnaires, :phone_number, :string
    add_column :personal_questionnaires, :pronouns, :string
    add_column :personal_questionnaires, :race_and_ethnicities, :string
    add_column :personal_questionnaires, :drivers_license_status, :string
    add_column :personal_questionnaires, :emergency_contact_name, :string
    add_column :personal_questionnaires, :emergency_contact_phone_number, :string
    add_column :personal_questionnaires, :emergency_contact_relationship, :string
    add_column :personal_questionnaires, :emergency_contact_2_name, :string
    add_column :personal_questionnaires, :emergency_contact_2_phone_number, :string
    add_column :personal_questionnaires, :emergency_contact_2_relationship, :string
    add_column :personal_questionnaires, :significant_relationships, :string
    add_column :personal_questionnaires, :support_systems, :string
    add_column :personal_questionnaires, :mental_health, :string
    add_column :personal_questionnaires, :DOC_status, :string
    add_column :personal_questionnaires, :DOC_regulations, :string
    add_column :personal_questionnaires, :housing, :string
    add_column :personal_questionnaires, :medical, :string
    add_column :personal_questionnaires, :treatment, :string
    add_column :personal_questionnaires, :triggers_and_prevention, :string
    add_column :personal_questionnaires, :personal_needs, :string
    add_column :personal_questionnaires, :transportation, :string
    add_column :personal_questionnaires, :clothing, :string
    add_column :personal_questionnaires, :financial_obligations, :string
    add_column :personal_questionnaires, :resources_allocated, :string
    add_column :personal_questionnaires, :orca_card, :string
    add_column :personal_questionnaires, :state_assistance, :string
    add_column :personal_questionnaires, :personal_goals, :string
  end
end
